#!/bin/bash
export CM_BUILDTYPE=NIGHTLY;
./build-ose.sh -o3 -j10 xt907;
mv out/target/product/xt907/OSE-4.4.2-*.zip /home/www/devs/teamose/OSE/Nightlies/xt907; 
export CM_BUILDTYPE=NIGHTLY;
./build-ose.sh -o3 -j10 xt925;
mv out/target/product/xt925/OSE-4.4.2-*.zip /home/www/devs/teamose/OSE/Nightlies/xt925; 
export CM_BUILDTYPE=NIGHTLY;
./build-ose.sh -o3 -j10 xt926;
mv out/target/product/xt926/OSE-4.4.2-*.zip /home/www/devs/teamose/OSE/Nightlies/xt926; 
export CM_BUILDTYPE=NIGHTLY;
./build-ose.sh -o3 -j10 xt1060;
mv out/target/product/xt1060/OSE-4.4.2-*.zip /home/www/devs/teamose/OSE/Nightlies/xt1060;
export CM_BUILDTYPE=NIGHTLY;
./build-ose.sh -o3 -j10 xt1058;
mv out/target/product/xt1058/OSE-4.4.2-*.zip /home/www/devs/teamose/OSE/Nightlies/xt1058;
export CM_BUILDTYPE=NIGHTLY;
./build-ose.sh -o3 -j10 jfltevzw;
mv out/target/product/jfltevzw/OSE-4.4.2-*.zip /home/www/devs/teamose/OSE/Nightlies/jfltevzw; 
export CM_BUILDTYPE=NIGHTLY;
./build-ose.sh -o3 -j10 jflteatt;
mv out/target/product/jflteatt/OSE-4.4.2-*.zip /home/www/devs/teamose/OSE/Nightlies/jflteatt; 
export CM_BUILDTYPE=NIGHTLY;
./build-ose.sh -o3 -j10 dlx;
mv out/target/product/dlx/OSE-4.4.2-*.zip /home/www/devs/teamose/OSE/Nightlies/dlx; 
export CM_BUILDTYPE=NIGHTLY;
./build-ose.sh -o3 -j10 m7vzw;
mv out/target/product/m7vzw/OSE-4.4.2-*.zip /home/www/devs/teamose/OSE/Nightlies/m7vzw;
export CM_BUILDTYPE=NIGHTLY;
./build-ose.sh -o3 -j10 m7att;
mv out/target/product/m7att/OSE-4.4.2-*.zip /home/www/devs/teamose/OSE/Nightlies/m7att;
export CM_BUILDTYPE=NIGHTLY;
./build-ose.sh -o3 -j10 d2vzw;
mv out/target/product/d2vzw/OSE-4.4.2-*.zip /home/www/devs/teamose/OSE/Nightlies/d2vzw;
export CM_BUILDTYPE=NIGHTLY;
./build-ose.sh -o3 -j10 d2att;
mv out/target/product/d2att/OSE-4.4.2-*.zip /home/www/devs/teamose/OSE/Nightlies/d2att; 
export CM_BUILDTYPE=NIGHTLY;
./build-ose.sh -o3 -j10 vs980;
mv out/target/product/vs980/OSE-4.4.2-*.zip /home/www/devs/teamose/OSE/Nightlies/vs980;
export CM_BUILDTYPE=NIGHTLY;
./build-ose.sh -o3 -j10 d802;
mv out/target/product/d802/OSE-4.4.2-*.zip /home/www/devs/teamose/OSE/Nightlies/d802;
export CM_BUILDTYPE=NIGHTLY;
./build-ose.sh -o3 -j10 hammerhead;
mv out/target/product/hammerhead/OSE-4.4.2-*.zip /home/www/devs/teamose/OSE/Nightlies/hammerhead;

