#!/bin/bash
export OSE_BUILD_TYPE=NIGHTLY;
./build-ose.sh -o3 -j18 grouper;
mv out/target/product/grouper/OSE-4.4.2-*.zip /home/www/devs/teamose/OSE/Nightlies/grouper; 
export OSE_BUILD_TYPE=NIGHTLY;
./build-ose.sh -o3 -j18 mb886;
mv out/target/product/mb886/OSE-4.4.2-*.zip /home/www/devs/teamose/OSE/Nightlies/mb886; 
export OSE_BUILD_TYPE=NIGHTLY;
./build-ose.sh -o3 -j18 t0lteatt;
mv out/target/product/t0lteatt/OSE-4.4.2-*.zip /home/www/devs/teamose/OSE/Nightlies/t0lteatt; 
export OSE_BUILD_TYPE=NIGHTLY;
./build-ose.sh -o3 -j18 d2cri;
mv out/target/product/d2cri/OSE-4.4.2-*.zip /home/www/devs/teamose/OSE/Nightlies/d2cri; 
export OSE_BUILD_TYPE=NIGHTLY;
./build-ose.sh -o3 -j18 d2mtr;
mv out/target/product/d2mtr/OSE-4.4.2-*.zip /home/www/devs/teamose/OSE/Nightlies/d2mtr; 
export OSE_BUILD_TYPE=NIGHTLY;
./build-ose.sh -o3 -j18 d2spr;
mv out/target/product/d2spr/OSE-4.4.2-*.zip /home/www/devs/teamose/OSE/Nightlies/d2spr;
export OSE_BUILD_TYPE=NIGHTLY;
./build-ose.sh -o3 -j18 d2tmo;
mv out/target/product/d2tmo/OSE-4.4.2-*.zip /home/www/devs/teamose/OSE/Nightlies/d2tmo;
export OSE_BUILD_TYPE=NIGHTLY;
./build-ose.sh -o3 -j18 d800;
mv out/target/product/d800/OSE-4.4.2-*.zip /home/www/devs/teamose/OSE/Nightlies/d800; 
export OSE_BUILD_TYPE=NIGHTLY;
./build-ose.sh -o3 -j18 jfltecan;
mv out/target/product/jfltecan/OSE-4.4.2-*.zip /home/www/devs/teamose/OSE/Nightlies/jfltecan;
export OSE_BUILD_TYPE=NIGHTLY;
./build-ose.sh -o3 -j18 jfltecri;
mv out/target/product/jfltecri/OSE-4.4.2-*.zip /home/www/devs/teamose/OSE/Nightlies/jfltecri; 
export OSE_BUILD_TYPE=NIGHTLY;
./build-ose.sh -o3 -j18 jfltecsp;
mv out/target/product/jfltecsp/OSE-4.4.2-*.zip /home/www/devs/teamose/OSE/Nightlies/jfltecsp;
export OSE_BUILD_TYPE=NIGHTLY;
./build-ose.sh -o3 -j18 jfltespr;
mv out/target/product/jfltespr/OSE-4.4.2-*.zip /home/www/devs/teamose/OSE/Nightlies/jfltespr; 
export OSE_BUILD_TYPE=NIGHTLY;
./build-ose.sh -o3 -j18 jfltetmo;
mv out/target/product/jfltetmo/OSE-4.4.2-*.zip /home/www/devs/teamose/OSE/Nightlies/jfltetmo; 
export OSE_BUILD_TYPE=NIGHTLY;
./build-ose.sh -o3 -j18 jflteusc;
mv out/target/product/jflteusc/OSE-4.4.2-*.zip /home/www/devs/teamose/OSE/Nightlies/jflteusc; 
export OSE_BUILD_TYPE=NIGHTLY;
./build-ose.sh -o3 -j18 ls970;
mv out/target/product/ls970/OSE-4.4.2-*.zip /home/www/devs/teamose/OSE/Nightlies/ls970;
export OSE_BUILD_TYPE=NIGHTLY;
./build-ose.sh -o3 -j18 m7spr;
mv out/target/product/m7spr/OSE-4.4.2-*.zip /home/www/devs/teamose/OSE/Nightlies/m7spr; 
export OSE_BUILD_TYPE=NIGHTLY;
./build-ose.sh -o3 -j18 m7tmo;
mv out/target/product/m7tmo/OSE-4.4.2-*.zip /home/www/devs/teamose/OSE/Nightlies/m7tmo; 
export OSE_BUILD_TYPE=NIGHTLY;
./build-ose.sh -o3 -j18 m7ul;
mv out/target/product/m7ul/OSE-4.4.2-*.zip /home/www/devs/teamose/OSE/Nightlies/m7ul; 
export OSE_BUILD_TYPE=NIGHTLY;
./build-ose.sh -o3 -j18 xt1053;
mv out/target/product/xt1053/OSE-4.4.2-*.zip /home/www/devs/teamose/OSE/Nightlies/xt1053; 